apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -o petclinic_chart/templates
    kompose.image-pull-secret: regcred
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: customers-service
  name: customers-service
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: customers-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml -o petclinic_chart/templates
        kompose.image-pull-secret: regcred
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: customers-service
    spec:
      containers:
        - image: '{{ .Values.IMAGE_TAG_CUSTOMERS_SERVICE }}'
          name: customers-service
          ports:
            - containerPort: 8081
              protocol: TCP
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
